// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: health.sql

package mysqlsqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
