// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mysqlsqlc

import (
	"time"
)

type PublicUrl struct {
	ID        uint64    `json:"id"`
	UrlKey    string    `json:"url_key"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
