// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package mysqlsqlc

import (
	"database/sql"
	"time"
)

type PublicUrl struct {
	ID        uint64    `json:"id"`
	UrlKey    string    `json:"url_key"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	// UUID v7（アプリケーション内部ID）
	ID []byte `json:"id"`
	// Firebase UID
	FirebaseUid string `json:"firebase_uid"`
	// メールアドレス
	Email string `json:"email"`
	// メール確認済みフラグ（Firebaseから取得）
	EmailVerified bool `json:"email_verified"`
	// 表示名（Firebaseから取得）
	DisplayName sql.NullString `json:"display_name"`
	// プロフィール画像URL（Firebaseから取得）
	PhotoUrl sql.NullString `json:"photo_url"`
	// 電話番号（Firebaseから取得、オプション）
	PhoneNumber sql.NullString `json:"phone_number"`
	// 認証プロバイダーID（例: google.com）
	ProviderID string `json:"provider_id"`
	// Firebase上のアカウント作成日時
	FirebaseCreatedAt sql.NullTime `json:"firebase_created_at"`
	// Firebase上の最終サインイン日時
	FirebaseLastSignInAt sql.NullTime `json:"firebase_last_sign_in_at"`
	// 自己紹介（アプリケーション独自項目）
	Bio sql.NullString `json:"bio"`
	// アクティブ状態
	IsActive bool `json:"is_active"`
	// メール確認日時（アプリケーション側で管理）
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
	// 最終ログイン日時（アプリケーション側で管理）
	LastLoginAt sql.NullTime `json:"last_login_at"`
	// 作成日時
	CreatedAt time.Time `json:"created_at"`
	// 更新日時
	UpdatedAt time.Time `json:"updated_at"`
	// 削除日時（論理削除用）
	DeletedAt sql.NullTime `json:"deleted_at"`
}
