// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    firebase_uid,
    email,
    email_verified,
    display_name,
    photo_url,
    phone_number,
    provider_id,
    firebase_created_at,
    firebase_last_sign_in_at,
    bio,
    is_active,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID                   []byte         `json:"id"`
	FirebaseUid          string         `json:"firebase_uid"`
	Email                string         `json:"email"`
	EmailVerified        bool           `json:"email_verified"`
	DisplayName          sql.NullString `json:"display_name"`
	PhotoUrl             sql.NullString `json:"photo_url"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	ProviderID           string         `json:"provider_id"`
	FirebaseCreatedAt    sql.NullTime   `json:"firebase_created_at"`
	FirebaseLastSignInAt sql.NullTime   `json:"firebase_last_sign_in_at"`
	Bio                  sql.NullString `json:"bio"`
	IsActive             bool           `json:"is_active"`
	EmailVerifiedAt      sql.NullTime   `json:"email_verified_at"`
	LastLoginAt          sql.NullTime   `json:"last_login_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.FirebaseUid,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.PhoneNumber,
		arg.ProviderID,
		arg.FirebaseCreatedAt,
		arg.FirebaseLastSignInAt,
		arg.Bio,
		arg.IsActive,
		arg.EmailVerifiedAt,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    firebase_uid,
    email,
    email_verified,
    display_name,
    photo_url,
    phone_number,
    provider_id,
    firebase_created_at,
    firebase_last_sign_in_at,
    bio,
    is_active,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.PhoneNumber,
		&i.ProviderID,
		&i.FirebaseCreatedAt,
		&i.FirebaseLastSignInAt,
		&i.Bio,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT
    id,
    firebase_uid,
    email,
    email_verified,
    display_name,
    photo_url,
    phone_number,
    provider_id,
    firebase_created_at,
    firebase_last_sign_in_at,
    bio,
    is_active,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE firebase_uid = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.PhoneNumber,
		&i.ProviderID,
		&i.FirebaseCreatedAt,
		&i.FirebaseLastSignInAt,
		&i.Bio,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    firebase_uid,
    email,
    email_verified,
    display_name,
    photo_url,
    phone_number,
    provider_id,
    firebase_created_at,
    firebase_last_sign_in_at,
    bio,
    is_active,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.PhoneNumber,
		&i.ProviderID,
		&i.FirebaseCreatedAt,
		&i.FirebaseLastSignInAt,
		&i.Bio,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserFromFirebase = `-- name: UpdateUserFromFirebase :execresult
UPDATE users
SET
    email = ?,
    email_verified = ?,
    display_name = ?,
    photo_url = ?,
    phone_number = ?,
    provider_id = ?,
    firebase_created_at = ?,
    firebase_last_sign_in_at = ?,
    last_login_at = ?,
    updated_at = ?
WHERE firebase_uid = ? AND deleted_at IS NULL
`

type UpdateUserFromFirebaseParams struct {
	Email                string         `json:"email"`
	EmailVerified        bool           `json:"email_verified"`
	DisplayName          sql.NullString `json:"display_name"`
	PhotoUrl             sql.NullString `json:"photo_url"`
	PhoneNumber          sql.NullString `json:"phone_number"`
	ProviderID           string         `json:"provider_id"`
	FirebaseCreatedAt    sql.NullTime   `json:"firebase_created_at"`
	FirebaseLastSignInAt sql.NullTime   `json:"firebase_last_sign_in_at"`
	LastLoginAt          sql.NullTime   `json:"last_login_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	FirebaseUid          string         `json:"firebase_uid"`
}

func (q *Queries) UpdateUserFromFirebase(ctx context.Context, arg UpdateUserFromFirebaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserFromFirebase,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.PhoneNumber,
		arg.ProviderID,
		arg.FirebaseCreatedAt,
		arg.FirebaseLastSignInAt,
		arg.LastLoginAt,
		arg.UpdatedAt,
		arg.FirebaseUid,
	)
}
