// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: profile.sql

package sqlc

import (
	"context"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id, name, nickname)
VALUES (?, ?, ?)
`

type CreateProfileParams struct {
	ID       string
	Name     string
	Nickname string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile, arg.ID, arg.Name, arg.Nickname)
	return err
}
