{
  "openapi": "3.0.3",
  "info": {
    "title": "Manager Backend API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/api"
    }
  ],
  "paths": {
    "/health": {
      "get": {
        "operationId": "GetHealth",
        "summary": "Get the current health status",
        "responses": {
          "200": {
            "description": "Successful health response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HealthResponseEnvelope"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "HealthResponseEnvelope": {
        "type": "object",
        "required": [
          "status",
          "data"
        ],
        "properties": {
          "status": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/HealthStatus"
          },
          "error": {
            "type": "object",
            "nullable": true,
            "properties": {
              "code": {
                "type": "string"
              },
              "message": {
                "type": "string"
              }
            }
          },
          "meta": {
            "type": "object",
            "nullable": true
          }
        }
      },
      "HealthStatus": {
        "type": "object",
        "required": [
          "status",
          "checked_at"
        ],
        "properties": {
          "status": {
            "type": "string"
          },
          "checked_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}
