// Code generated by cmd/openapi; DO NOT EDIT.

package openapi

import (
	"github.com/labstack/echo/v4"
	"time"
)

type HealthResponseEnvelope struct {
	Data   HealthStatus                 `json:"data"`
	Error  *HealthResponseEnvelopeError `json:"error"`
	Meta   map[string]interface{}       `json:"meta"`
	Status string                       `json:"status"`
}

type HealthStatus struct {
	CheckedAt time.Time `json:"checked_at"`
	Status    string    `json:"status"`
}

type HealthResponseEnvelopeError struct {
	Code    *string `json:"code"`
	Message *string `json:"message"`
}

type ServerInterface interface {
	GetHealth(ctx echo.Context) error
}

func RegisterHandlers(g *echo.Group, si ServerInterface) {
	if g == nil {
		panic("nil echo group")
	}
	if si == nil {
		panic("nil server implementation")
	}

	g.GET("/health", si.GetHealth)
}
