// Code generated by cmd/openapi; DO NOT EDIT.

package openapi

import (
	"github.com/labstack/echo/v4"
	"time"
)

type ErrorBody struct {
	Code      *string       `json:"code"`
	Details   []interface{} `json:"details"`
	Message   *string       `json:"message"`
	RequestId string        `json:"requestId"`
}

type ErrorDetail struct {
	Code    *string `json:"code"`
	Field   *string `json:"field"`
	Message *string `json:"message"`
}

type ErrorResponse interface{}

type HealthStatus struct {
	CheckedAt time.Time `json:"checked_at"`
	Status    string    `json:"status"`
}

type HealthSuccessResponse interface{}

type ResponseEnvelope struct {
	Data   *interface{} `json:"data"`
	Error  *interface{} `json:"error"`
	Meta   *interface{} `json:"meta"`
	Status string       `json:"status"`
}

type ServerInterface interface {
	GetHealth(ctx echo.Context) error
}

func RegisterHandlers(g *echo.Group, si ServerInterface) {
	if g == nil {
		panic("nil echo group")
	}
	if si == nil {
		panic("nil server implementation")
	}

	g.GET("/health", si.GetHealth)
}
